# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPublish < Formula
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hadlow/go-publish/releases/download/v1.0.5/hadlow-go-publish_Darwin_x86_64.tar.gz"
      sha256 "0f6e818d5a7c6c4bac40766fe7d261badf4da5d22b3b70a1e50f729cce8a532b"

      def install
        bin.install "go-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hadlow/go-publish/releases/download/v1.0.5/hadlow-go-publish_Darwin_arm64.tar.gz"
      sha256 "05a766dfd15c18694eaffc1b9d700cc092a6569f0a6bf9b69710d081ef7db033"

      def install
        bin.install "go-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/go-publish/releases/download/v1.0.5/hadlow-go-publish_Linux_x86_64.tar.gz"
        sha256 "ddf5a7cf1ff71cc93a2f7cdf684b19446dfd2a108148327524eebf5deafe2f85"

        def install
          bin.install "go-publish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/go-publish/releases/download/v1.0.5/hadlow-go-publish_Linux_arm64.tar.gz"
        sha256 "7ff7ae00b0fc2b6970221d5690c8f161927d44b9fe0320adc99012614eb45071"

        def install
          bin.install "go-publish"
        end
      end
    end
  end

  test do
    system "#{bin}/go-publish --version"
  end
end
