# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopublish < Formula
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hadlow/gopublish/releases/download/v1.0.0/hadlow-gopublish_Darwin_x86_64.tar.gz"
      sha256 "6d570191ae0fc5a2d1fdf4997448a728f7fefdb169e57da687ba8ec81145e697"

      def install
        bin.install "gopublish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hadlow/gopublish/releases/download/v1.0.0/hadlow-gopublish_Darwin_arm64.tar.gz"
      sha256 "2aa0fcb36b8fb6607a4e37d3466f08ebfe27ba9e5d3d1f38e9948e3ac5d24a7d"

      def install
        bin.install "gopublish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/gopublish/releases/download/v1.0.0/hadlow-gopublish_Linux_x86_64.tar.gz"
        sha256 "8b080db8c1d3af46d350acce288dc2ad2519142f4e8987a2fea318c2b8c300af"

        def install
          bin.install "gopublish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/gopublish/releases/download/v1.0.0/hadlow-gopublish_Linux_arm64.tar.gz"
        sha256 "16696d381e78cdbd7fcc8fff24382461aa8cc54d6fc08611b858d81451b354f8"

        def install
          bin.install "gopublish"
        end
      end
    end
  end

  test do
    system "#{bin}/gopublish --version"
  end
end
