# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopublish < Formula
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hadlow/gopublish/releases/download/v1.0.1/gopublish_Darwin_x86_64.tar.gz"
      sha256 "a32c8840bc71ac88b3e7a8017355d3b3a0c3f0d8f1ca7b92b64db084f8f299a9"

      def install
        bin.install "gopublish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hadlow/gopublish/releases/download/v1.0.1/gopublish_Darwin_arm64.tar.gz"
      sha256 "b13de9cf3f3eae752347c0849d2c0f9e1cb1edee40029db49c62b1c4ed2b02b4"

      def install
        bin.install "gopublish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/gopublish/releases/download/v1.0.1/gopublish_Linux_x86_64.tar.gz"
        sha256 "0674ea50ad8c44075d684fc7ae2da82969247e09ebf718ebcb3a8b197eb92616"

        def install
          bin.install "gopublish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/gopublish/releases/download/v1.0.1/gopublish_Linux_arm64.tar.gz"
        sha256 "0a3d45c2b18106c35a30880b2b32088c90eba7c9d60430f58afb4903fe26d29c"

        def install
          bin.install "gopublish"
        end
      end
    end
  end

  test do
    system "#{bin}/gopublish --version"
  end
end
